title: "My Academic Site"
baseurl: ""           # repository root
markdown: kramdown

nav_items:
  - name: Home
    url: /
  - name: Research
    url: /research/
  - name: Publications
    url: /publications/
  - name: Talks
    url: /talks/
  - name: Teaching
    url: /teaching/
  - name: Blog
    url: /blog/
  - name: CV
    url: /cv/
  - name: Misc
    url: /misc/
  - name: FAQ
    url: /faq/